
------ Task 1

CREATE TABLESPACE myspace
DATAFILE 'D:\DBMS\data.dbf' SIZE 1M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE TABLESPACE myspace2
DATAFILE 'D:\DBMS\data2.dbf' SIZE 1M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE USER user1 IDENTIFIED BY test123
DEFAULT TABLESPACE myspace;

GRANT CREATE SESSION TO user1;
GRANT CREATE TABLE TO user1;
GRANT UNLIMITED TABLESPACE TO user1;

DISC;

CONNECT user1 test123;

CREATE TABLE T1(
ID NUMBER PRIMARY KEY,
NAME VARCHAR2(15))
TABLESPACE myspace;

CREATE TABLE T2(
ID NUMBER PRIMARY KEY,
NAME VARCHAR2(15))
TABLESPACE myspace;

CREATE TABLE T3(
ID NUMBER PRIMARY KEY,
NAME VARCHAR2(15),
YEAR_ID NUMBER,
CONSTRAINTS FK2 FOREIGN KEY (YEAR_ID) REFERENCES T2)
TABLESPACE myspace;

CREATE TABLE T4(
ID NUMBER PRIMARY KEY,
NAME VARCHAR2(15))
TABLESPACE myspace2;


------ Task 2

INSERT INTO T1(ID,NAME) VALUES (11,'T1A');
INSERT INTO T1(ID,NAME) VALUES (12,'T1B');
INSERT INTO T1(ID,NAME) VALUES (13,'T1C');
INSERT INTO T1(ID,NAME) VALUES (14,'T1D');
INSERT INTO T1(ID,NAME) VALUES (15,'T1E');

INSERT INTO T2(ID,NAME) VALUES (21,'T2A');
INSERT INTO T2(ID,NAME) VALUES (22,'T2B');
INSERT INTO T2(ID,NAME) VALUES (23,'T2C');
INSERT INTO T2(ID,NAME) VALUES (24,'T2D');
INSERT INTO T2(ID,NAME) VALUES (25,'T2E');
INSERT INTO T2(ID,NAME) VALUES (26,'T2F');

INSERT INTO T3(ID,NAME,YEAR_ID) VALUES (31,'T3A',21);
INSERT INTO T3(ID,NAME,YEAR_ID) VALUES (32,'T3B',22);
INSERT INTO T3(ID,NAME,YEAR_ID) VALUES (33,'T3C',23);
INSERT INTO T3(ID,NAME,YEAR_ID) VALUES (34,'T3D',24);
INSERT INTO T3(ID,NAME,YEAR_ID) VALUES (35,'T3E',25);
INSERT INTO T3(ID,YEAR_ID) VALUES (36,25);

INSERT INTO T4(ID,NAME) VALUES (41,'T4A');
INSERT INTO T4(ID,NAME) VALUES (42,'T4B');
INSERT INTO T4(ID,NAME) VALUES (43,'T4C');
INSERT INTO T4(ID,NAME) VALUES (44,'T4D');
INSERT INTO T4(ID,NAME) VALUES (45,'T4E');

-- Nested Subquery
SELECT ID, NAME
FROM T2
WHERE ID IN(
SELECT YEAR_ID
FROM T3);

-- Inline View
SELECT YEAR_ID AS T3_YID
FROM(
SELECT YEAR_ID
FROM T3);

------ Task 3

-- Left Outer Join
SELECT *
FROM T2
LEFT JOIN T3 ON T2.ID = T3.YEAR_ID;
-- Right Outer Join
SELECT *
FROM T2
RIGHT JOIN T3 ON T2.ID = T3.YEAR_ID;
-- Natural Join
SELECT *
FROM T3
INNER JOIN T2
ON T2.ID = T3.YEAR_ID;









